using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Reflection;
using System.Text;

namespace DNXServer.Action
{
	public class SuddenDeath : BaseAction
	{
		public string SkillID;
		public string SkillName;
		public string Description;
		public int Type;
		public int Category;
		public string MissMessage;
		public string ToSelfIncrease;
		public string ToOpponentReduce;
		public int ToOpponentStatus;
		public double ToSelfHPMin;
		public double ToSelfHPMax;
		public double ToSelfHPRegenMin;
		public double ToSelfHPRegenMax;
		public double ToSelfMPMin;
		public double ToSelfMPMax;
		public double ToSelfMPRegenMin;
		public double ToSelfMPRegenMax;
		public double ToSelfSPDMin;
		public double ToSelfSPDMax;
		public double ToSelfPATKMin;
		public double ToSelfPATKMax;
		public double ToSelfMATKMin;
		public double ToSelfMATKMax;
		public double ToSelfPDEFMin;
		public double ToSelfPDEFMax;
		public double ToSelfMDEFMin;
		public double ToSelfMDEFMax;
		public double ToSelfACCMin;
		public double ToSelfACCMax;
		public double ToSelfEVAMin;
		public double ToSelfEVAMax;
		public double ToSelfCRITMin;
		public double ToSelfCRITMax;
		public double ToSelfEffectSPDMin;
		public double ToSelfEffectSPDMax;
		public double ToSelfEffectPATKMin;
		public double ToSelfEffectPATKMax;
		public double ToSelfEffectMATKMin;
		public double ToSelfEffectMATKMax;
		public double ToSelfEffectPDEFMin;
		public double ToSelfEffectPDEFMax;
		public double ToSelfEffectMDEFMin;
		public double ToSelfEffectMDEFMax;
		public double ToSelfEffectACCMin;
		public double ToSelfEffectACCMax;
		public double ToSelfEffectEVAMin;
		public double ToSelfEffectEVAMax;
		public double ToSelfEffectCRITMin;
		public double ToSelfEffectCRITMax;
		public double ToOpponentHPMin;
		public double ToOpponentHPMax;
		public double ToOpponentHPRegenMin;
		public double ToOpponentHPRegenMax;
		public double ToOpponentMPMin;
		public double ToOpponentMPMax;
		public double ToOpponentMPRegenMin;
		public double ToOpponentMPRegenMax;
		public double ToOpponentSPDMin;
		public double ToOpponentSPDMax;
		public double ToOpponentPATKMin;
		public double ToOpponentPATKMax;
		public double ToOpponentMATKMin;
		public double ToOpponentMATKMax;
		public double ToOpponentPDEFMin;
		public double ToOpponentPDEFMax;
		public double ToOpponentMDEFMin;
		public double ToOpponentMDEFMax;
		public double ToOpponentACCMin;
		public double ToOpponentACCMax;
		public double ToOpponentEVAMin;
		public double ToOpponentEVAMax;
		public double ToOpponentCRITMin;
		public double ToOpponentCRITMax;
		public double ToSelfContinuousHPMin;
		public double ToSelfContinuousHPMax;
		public double ToSelfContinuousHPRegenMin;
		public double ToSelfContinuousHPRegenMax;
		public double ToSelfContinuousMPMin;
		public double ToSelfContinuousMPMax;
		public double ToSelfContinuousMPRegenMin;
		public double ToSelfContinuousMPRegenMax;
		public double ToSelfContinuousSPDMin;
		public double ToSelfContinuousSPDMax;
		public double ToSelfContinuousPATKMin;
		public double ToSelfContinuousPATKMax;
		public double ToSelfContinuousMATKMin;
		public double ToSelfContinuousMATKMax;
		public double ToSelfContinuousPDEFMin;
		public double ToSelfContinuousPDEFMax;
		public double ToSelfContinuousMDEFMin;
		public double ToSelfContinuousMDEFMax;
		public double ToSelfContinuousACCMin;
		public double ToSelfContinuousACCMax;
		public double ToSelfContinuousEVAMin;
		public double ToSelfContinuousEVAMax;
		public double ToSelfContinuousCRITMin;
		public double ToSelfContinuousCRITMax;
		public double ToOpponentContinuousHPMin;
		public double ToOpponentContinuousHPMax;
		public double ToOpponentContinuousHPRegenMin;
		public double ToOpponentContinuousHPRegenMax;
		public double ToOpponentContinuousMPMin;
		public double ToOpponentContinuousMPMax;
		public double ToOpponentContinuousMPRegenMin;
		public double ToOpponentContinuousMPRegenMax;
		public double ToOpponentContinuousSPDMin;
		public double ToOpponentContinuousSPDMax;
		public double ToOpponentContinuousPATKMin;
		public double ToOpponentContinuousPATKMax;
		public double ToOpponentContinuousMATKMin;
		public double ToOpponentContinuousMATKMax;
		public double ToOpponentContinuousPDEFMin;
		public double ToOpponentContinuousPDEFMax;
		public double ToOpponentContinuousMDEFMin;
		public double ToOpponentContinuousMDEFMax;
		public double ToOpponentContinuousACCMin;
		public double ToOpponentContinuousACCMax;
		public double ToOpponentContinuousEVAMin;
		public double ToOpponentContinuousEVAMax;
		public double ToOpponentContinuousCRITMin;
		public double ToOpponentContinuousCRITMax;
		public int EffectLifetime;
		public int SkillCooldown;
		public string AnimationName;
		public string ReactionName;
		public string SelfEffectName;
		public int SelfEffectAttachedTo;
		public int SelfEffectPlayAt;
		public string OpponentEffectName;
		public int OpponentEffectAttachedTo;
		public string StatusInflicted;

		public SuddenDeath(string skillID)
		{
			StringDictionary suddenDeath;
			using (Command ("SELECT * FROM sudden_death WHERE skill_id = :skill")) 
			{
				SilentAddParameter("skill", skillID);
				suddenDeath = SilentExecuteRow();
			}

			this.SkillID = skillID;
			this.SkillName = suddenDeath ["skill_name"];
			this.Description = suddenDeath ["description"];
			this.Type = Convert.ToInt32 (suddenDeath["type"]);
			this.Category = Convert.ToInt32 (suddenDeath ["category"]);
			this.MissMessage = suddenDeath["miss_message"];
			this.ToSelfIncrease = suddenDeath ["to_self_increase"];
			this.ToOpponentReduce = suddenDeath ["to_opponent_reduce"];
			this.ToOpponentStatus = Convert.ToInt32(suddenDeath ["to_opponent_status"]);
			this.ToSelfHPMin = Convert.ToDouble (suddenDeath ["to_self_hp_min"]);
			this.ToSelfHPMax = Convert.ToDouble (suddenDeath ["to_self_hp_max"]);
			this.ToSelfHPRegenMin = Convert.ToDouble (suddenDeath ["to_self_hp_regen_min"]);
			this.ToSelfHPRegenMax = Convert.ToDouble (suddenDeath ["to_self_hp_regen_max"]);
			this.ToSelfMPMin = Convert.ToDouble (suddenDeath ["to_self_mp_min"]);
			this.ToSelfMPMax = Convert.ToDouble (suddenDeath ["to_self_mp_max"]);
			this.ToSelfMPRegenMin = Convert.ToDouble (suddenDeath ["to_self_mp_regen_min"]);
			this.ToSelfMPRegenMax = Convert.ToDouble (suddenDeath ["to_self_mp_regen_max"]);
			this.ToSelfSPDMin = Convert.ToDouble (suddenDeath ["to_self_spd_min"]);
			this.ToSelfSPDMax = Convert.ToDouble (suddenDeath ["to_self_spd_max"]);
			this.ToSelfPATKMin = Convert.ToDouble (suddenDeath ["to_self_patk_min"]);
			this.ToSelfPATKMax = Convert.ToDouble (suddenDeath ["to_self_patk_max"]);
			this.ToSelfMATKMin = Convert.ToDouble (suddenDeath ["to_self_matk_min"]);
			this.ToSelfMATKMax = Convert.ToDouble (suddenDeath ["to_self_matk_max"]);
			this.ToSelfPDEFMin = Convert.ToDouble (suddenDeath ["to_self_pdef_min"]);
			this.ToSelfPDEFMax = Convert.ToDouble (suddenDeath ["to_self_pdef_max"]);
			this.ToSelfMDEFMin = Convert.ToDouble (suddenDeath ["to_self_mdef_min"]);
			this.ToSelfMDEFMax = Convert.ToDouble (suddenDeath ["to_self_mdef_max"]);
			this.ToSelfACCMin = Convert.ToDouble (suddenDeath ["to_self_acc_min"]);
			this.ToSelfACCMax = Convert.ToDouble (suddenDeath ["to_self_acc_max"]);
			this.ToSelfEVAMin = Convert.ToDouble (suddenDeath ["to_self_eva_min"]);
			this.ToSelfEVAMax = Convert.ToDouble (suddenDeath ["to_self_eva_max"]);
			this.ToSelfCRITMin = Convert.ToDouble (suddenDeath ["to_self_cri_min"]);
			this.ToSelfCRITMax = Convert.ToDouble (suddenDeath ["to_self_cri_max"]);
			this.ToSelfEffectSPDMin = Convert.ToDouble (suddenDeath ["to_self_effect_spd_min"]);
			this.ToSelfEffectSPDMax = Convert.ToDouble (suddenDeath ["to_self_effect_spd_max"]);
			this.ToSelfEffectPATKMin = Convert.ToDouble (suddenDeath ["to_self_effect_patk_min"]);
			this.ToSelfEffectPATKMax = Convert.ToDouble (suddenDeath ["to_self-effect_patk_max"]);
			this.ToSelfEffectMATKMin = Convert.ToDouble (suddenDeath ["to_self_effect_matk_min"]);
			this.ToSelfEffectMATKMax = Convert.ToDouble (suddenDeath ["to_self_effect_matk_max"]);
			this.ToSelfEffectPDEFMin = Convert.ToDouble (suddenDeath ["to_self_effect_pdef_min"]);
			this.ToSelfEffectPDEFMax = Convert.ToDouble (suddenDeath ["to_self_effect_pdef_max"]);
			this.ToSelfEffectMDEFMin = Convert.ToDouble (suddenDeath ["to_self_effect_mdef_min"]);
			this.ToSelfEffectMDEFMax = Convert.ToDouble (suddenDeath["to_self_effect_mdef_max"]);
			this.ToSelfEffectACCMin = Convert.ToDouble (suddenDeath["to_self_effect_acc_min"]);
			this.ToSelfEffectACCMax = Convert.ToDouble (suddenDeath ["to_self_effect_acc_max"]);
			this.ToSelfEffectEVAMin = Convert.ToDouble (suddenDeath ["to_self_effect_eva_min"]);
			this.ToSelfEffectEVAMax = Convert.ToDouble (suddenDeath ["to_self_effect_eva_max"]);
			this.ToSelfEffectCRITMin = Convert.ToDouble (suddenDeath ["to_self_effect_cri_min"]);
			this.ToSelfEffectCRITMax = Convert.ToDouble (suddenDeath ["to_self_effect_cri_max"]);
			this.ToOpponentHPMin = Convert.ToDouble (suddenDeath ["to_opponent_hp_min"]);
			this.ToOpponentHPMax = Convert.ToDouble (suddenDeath ["to_opponent_hp_max"]);
			this.ToOpponentHPRegenMin = Convert.ToDouble (suddenDeath ["to_opponent_hp_regen_min"]);
			this.ToOpponentHPRegenMax = Convert.ToDouble (suddenDeath ["to_opponent_hp_regen_max"]);
			this.ToOpponentMPMin = Convert.ToDouble (suddenDeath ["to_opponent_mp_min"]);
			this.ToOpponentMPMax = Convert.ToDouble (suddenDeath ["to_opponent_mp_max"]);
			this.ToOpponentMPRegenMin = Convert.ToDouble (suddenDeath ["to_opponent_mp_regen_min"]);
			this.ToOpponentMPRegenMax = Convert.ToDouble (suddenDeath ["to_opponent_mp_regen_min"]);
			this.ToOpponentSPDMin = Convert.ToDouble (suddenDeath ["to_opponent_spd_min"]);
			this.ToOpponentSPDMax = Convert.ToDouble (suddenDeath ["to_opponent_spd_max"]);
			this.ToOpponentPATKMin = Convert.ToDouble (suddenDeath ["to_opponent_patk_min"]);
			this.ToOpponentPATKMax = Convert.ToDouble (suddenDeath ["to_opponent_patk_max"]);
			this.ToOpponentMATKMin = Convert.ToDouble (suddenDeath ["to_opponent_matk_min"]);
			this.ToOpponentMATKMax = Convert.ToDouble (suddenDeath ["to_opponent_matk_max"]);
			this.ToOpponentPDEFMin = Convert.ToDouble (suddenDeath ["to_opponent_pdef_min"]);
			this.ToOpponentPDEFMax = Convert.ToDouble (suddenDeath ["to_opponent_pdef_max"]);
			this.ToOpponentMDEFMin = Convert.ToDouble (suddenDeath ["to_opponent_mdef_min"]);
			this.ToOpponentMDEFMax = Convert.ToDouble (suddenDeath ["to_opponent_mdef_max"]);
			this.ToOpponentACCMin = Convert.ToDouble (suddenDeath ["to_opponent_acc_min"]);
			this.ToOpponentACCMax = Convert.ToDouble (suddenDeath ["to_opponent_acc_max"]);
			this.ToOpponentEVAMin = Convert.ToDouble (suddenDeath ["to_opponent_eva_min"]);
			this.ToOpponentEVAMax = Convert.ToDouble (suddenDeath ["to_opponent_eva_max"]);
			this.ToOpponentCRITMin = Convert.ToDouble (suddenDeath ["to_opponent_cri_min"]);
			this.ToOpponentCRITMax = Convert.ToDouble (suddenDeath ["to_opponent_cri_max"]);
			this.ToSelfContinuousHPMin = Convert.ToDouble (suddenDeath ["to_self_continuous_hp_min"]);
			this.ToSelfContinuousHPMax = Convert.ToDouble (suddenDeath ["to_self_continuous_hp_max"]);
			this.ToSelfContinuousHPRegenMin = Convert.ToDouble (suddenDeath ["to_slef_continuous_hp_regen_min"]);
			this.ToSelfContinuousHPRegenMax = Convert.ToDouble (suddenDeath ["to_self_continuous_hp_regen_max"]);
			this.ToSelfContinuousMPMin = Convert.ToDouble (suddenDeath ["to_self_continuous_mp_min"]);
			this.ToSelfContinuousMPMax = Convert.ToDouble (suddenDeath ["to_self_continuous_mp_max"]);
			this.ToSelfContinuousMPRegenMin = Convert.ToDouble (suddenDeath ["to_self_continuous_mp_regen_min"]);
			this.ToSelfContinuousMPRegenMax = Convert.ToDouble (suddenDeath ["to_self_continuous_mp_regen_max"]);
			this.ToSelfContinuousSPDMin = Convert.ToDouble (suddenDeath ["to_self_continuous_spd_min"]);
			this.ToSelfContinuousSPDMax = Convert.ToDouble (suddenDeath ["to_self_continuous_spd_max"]);
			this.ToSelfContinuousPATKMin = Convert.ToDouble (suddenDeath ["to_self_continuous_patk_min"]);
			this.ToSelfContinuousPATKMax = Convert.ToDouble (suddenDeath ["to_self_continuous_patk_max"]);
			this.ToSelfContinuousMATKMin = Convert.ToDouble (suddenDeath ["to_self_continuous_matk_min"]);
			this.ToSelfContinuousMATKMax = Convert.ToDouble (suddenDeath ["to_self_continuous_matk_max"]);
			this.ToSelfContinuousPDEFMin = Convert.ToDouble (suddenDeath ["to_self_continuous_pdef_min"]);
			this.ToSelfContinuousPDEFMax = Convert.ToDouble (suddenDeath ["to_self_continuous_pdef_max"]);
			this.ToSelfContinuousMDEFMin = Convert.ToDouble (suddenDeath ["to_self_continuous_mdef_min"]);
			this.ToSelfContinuousMDEFMax = Convert.ToDouble (suddenDeath ["to_self_continuous_mdef_max"]);
			this.ToSelfContinuousACCMin = Convert.ToDouble (suddenDeath ["to_self_continuous_acc_min"]);
			this.ToSelfContinuousACCMax = Convert.ToDouble (suddenDeath ["to_self_continuous_acc_max"]);
			this.ToSelfContinuousEVAMin = Convert.ToDouble (suddenDeath ["to_self_continuous_eva_min"]);
			this.ToSelfContinuousEVAMax = Convert.ToDouble (suddenDeath ["to_self_continuous_eva_max"]);
			this.ToSelfContinuousCRITMin = Convert.ToDouble (suddenDeath ["to_self_continuous_cri_min"]);
			this.ToSelfContinuousCRITMax = Convert.ToDouble (suddenDeath ["to_self_continuous_cri_max"]);
			this.ToOpponentContinuousHPMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_hp_min"]);
			this.ToOpponentContinuousHPMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_hp_max"]);
			this.ToOpponentContinuousHPRegenMin = Convert.ToDouble(suddenDeath["to_opponent_continuous_hp_regen_min"]);
			this.ToOpponentContinuousHPRegenMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_hp_regen_max"]);
			this.ToOpponentContinuousMPMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_mp_min"]);
			this.ToOpponentContinuousMPMax = Convert.ToDouble (suddenDeath ["to_opponent_contiuous_mp_max"]);
			this.ToOpponentContinuousMPRegenMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_mp_regen_min"]);
			this.ToOpponentContinuousMPRegenMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_mp_regen_max"]);
			this.ToOpponentContinuousSPDMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_spd_min"]);
			this.ToOpponentContinuousSPDMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_spd_max"]);
			this.ToOpponentContinuousPATKMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_patk_min"]);
			this.ToOpponentContinuousPATKMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_patk_max"]);
			this.ToOpponentContinuousMATKMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_matk_min"]);
			this.ToOpponentContinuousMATKMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_matk_max"]);
			this.ToOpponentContinuousPDEFMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_pdef_min"]);
			this.ToOpponentContinuousPDEFMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_pdef_max"]);
			this.ToOpponentContinuousMDEFMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_mdef_min"]);
			this.ToOpponentContinuousMDEFMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_mdef_max"]);
			this.ToOpponentContinuousACCMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_acc_min"]);
			this.ToOpponentContinuousACCMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_acc_max"]);
			this.ToOpponentContinuousEVAMin = Convert.ToDouble (suddenDeath ["to_opponent_contionuous_eva_min"]);
			this.ToOpponentContinuousEVAMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_eva_max"]);
			this.ToOpponentContinuousCRITMin = Convert.ToDouble (suddenDeath ["to_opponent_continuous_cri_min"]);
			this.ToOpponentContinuousCRITMax = Convert.ToDouble (suddenDeath ["to_opponent_continuous_cri_max"]);
			this.EffectLifetime = Convert.ToInt32 (suddenDeath ["effect_lifetime"]);
			this.SkillCooldown = Convert.ToInt32 (suddenDeath ["skill_cooldown"]);
			this.AnimationName = suddenDeath ["animation_name"];
			this.ReactionName = suddenDeath ["reaction_name"];
			this.SelfEffectName = suddenDeath ["self_effect_name"];
			this.SelfEffectAttachedTo = Convert.ToInt32 (suddenDeath ["self_effect_attached_to"]);
			this.SelfEffectPlayAt = Convert.ToInt32 (suddenDeath ["self_effect_play_at"]);
			this.OpponentEffectName = suddenDeath ["opponent_effect_name"];
			this.OpponentEffectAttachedTo = Convert.ToInt32 (suddenDeath ["opponent_effect_attached_to"]);
			this.StatusInflicted = suddenDeath ["status_inflicted"];
		}

		public int GetToOpponentCritical()
		{
			//return Util.Random (Convert.ToInt32 (t));
			return 0;
		}

	}
}

